// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("Style", "IDE0028:简化集合初始化", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.StagePage.#ctor")]
[assembly: SuppressMessage("Style", "IDE0028:简化集合初始化", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.Core.StaticObjManager.#cctor")]
[assembly: SuppressMessage("Style", "IDE0028:简化集合初始化", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.GamePage.#ctor")]
[assembly: SuppressMessage("Style", "IDE0300:简化集合初始化", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.GamePage.CheckWin")]
[assembly: SuppressMessage("Style", "IDE0017:简化对象初始化", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.SetNewStageWindow.SaveStage(System.Object,System.Windows.Input.MouseButtonEventArgs)")]
[assembly: SuppressMessage("Style", "IDE0028:简化集合初始化", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.MapEditWindow.#ctor")]
[assembly: SuppressMessage("Style", "IDE0019:使用模式匹配", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.MapEditWindow.ToolBar_Loaded(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE0019:使用模式匹配", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.MapEditWindow.ListBoxMouseButtonDown(System.Object,System.Windows.Input.MouseButtonEventArgs)")]
[assembly: SuppressMessage("Style", "IDE0300:简化集合初始化", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.MapEditWindow.NewStage(System.Object,System.Windows.Input.MouseButtonEventArgs)")]
[assembly: SuppressMessage("Style", "IDE0019:使用模式匹配", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.MapEditWindow.EditCurrentStage(System.Object,System.Windows.Input.MouseButtonEventArgs)")]
[assembly: SuppressMessage("Style", "IDE0300:简化集合初始化", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.MapEditWindow.EditCurrentStage(System.Object,System.Windows.Input.MouseButtonEventArgs)")]
[assembly: SuppressMessage("Style", "IDE0019:使用模式匹配", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.MapEditWindow.LayoutCurrentStage(System.Object,System.Windows.Input.MouseButtonEventArgs)")]
[assembly: SuppressMessage("Style", "IDE0063:使用简单的 \"using\" 语句", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.Core.Parser.XSBMapParser.#ctor")]
[assembly: SuppressMessage("Style", "IDE0028:简化集合初始化", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.Core.Parser.XSBMapParser.#ctor")]
[assembly: SuppressMessage("Style", "IDE0300:简化集合初始化", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.Core.Parser.XSBMapParser.#ctor")]
[assembly: SuppressMessage("Style", "IDE0071:简化内插", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.Core.Parser.XSBMapParser.SaveXSB(Sokoban.Model.Stage,System.String)")]
[assembly: SuppressMessage("Style", "IDE0305:简化集合初始化", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.StagePage.#ctor")]
[assembly: SuppressMessage("Style", "IDE0028:简化集合初始化", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.Componets.MessageManage.#cctor")]
[assembly: SuppressMessage("Style", "IDE0305:简化集合初始化", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.Utils.EncodingExtend.BaseConvert(System.Int32[],System.Int32,System.Int32)~System.Int32[]")]
[assembly: SuppressMessage("Style", "IDE0305:简化集合初始化", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.Utils.ExtendMethod.BytesTrimEnd(System.Byte[])~System.Byte[]")]
[assembly: SuppressMessage("Style", "IDE0090:使用 \"new(...)\"", Justification = "<挂起>", Scope = "member", Target = "~F:LogViewerLib.LogViewer.stringBuffers")]
[assembly: SuppressMessage("Style", "IDE0028:简化集合初始化", Justification = "<挂起>", Scope = "member", Target = "~F:LogViewerLib.LogViewer.stringBuffers")]
[assembly: SuppressMessage("Style", "IDE0018:内联变量声明", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.Notify.PropertyNotifyObject.GetPropertyValue``1(System.String)~``0")]
[assembly: SuppressMessage("Style", "IDE0028:简化集合初始化", Justification = "<挂起>", Scope = "member", Target = "~F:Sokoban.Notify.PropertyNotifyObject._ValueDictionary")]
[assembly: SuppressMessage("Style", "IDE0290:使用主构造函数", Justification = "<挂起>", Scope = "member", Target = "~M:LogViewerLib.StyledString.#ctor(System.String,LogViewerLib.StringStyleEnum,LogViewerLib.LineHandlingEnum)")]
[assembly: SuppressMessage("Style", "IDE0290:使用主构造函数", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.Model.MoveHistory.#ctor(Sokoban.Model.Coordinate,Sokoban.Model.Coordinate,Sokoban.Model.Direction)")]
[assembly: SuppressMessage("Style", "IDE0063:使用简单的 \"using\" 语句", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.Core.Parser.XSBMapParser.SaveLURD(Sokoban.Model.Stage,System.String)")]
[assembly: SuppressMessage("Style", "IDE0305:简化集合初始化", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.Core.Parser.XSBMapParser.LoadXSB(System.String)~Sokoban.Model.Stage")]
[assembly: SuppressMessage("Style", "IDE0071:简化内插", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.Core.Parser.XSBMapParser.SaveLURD(Sokoban.Model.Stage,System.String)")]
[assembly: SuppressMessage("Style", "IDE0028:简化集合初始化", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.Core.Parser.XSBMapParser.CreateHistroiesFromLURD(System.Byte[,],System.String)~Sokoban.Notify.ObservableStack{Sokoban.Model.MoveHistory}")]
[assembly: SuppressMessage("Style", "IDE0090:使用 \"new(...)\"", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.Core.Parser.XSBMapParser.GetMove(System.Byte[,],System.Char,Sokoban.Model.Coordinate@)~Sokoban.Model.MoveHistory")]
[assembly: SuppressMessage("Style", "IDE0090:使用 \"new(...)\"", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.Core.Parser.XSBMapParser.CreateHistroiesFromLURD(System.Byte[,],System.String)~Sokoban.Notify.ObservableStack{Sokoban.Model.MoveHistory}")]
[assembly: SuppressMessage("Style", "IDE0034:简化 \"default\" 表达式", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.Core.Parser.XSBMapParser.LoadLURD(System.String,Sokoban.Model.Stage)")]
[assembly: SuppressMessage("Style", "IDE0028:简化集合初始化", Justification = "<挂起>", Scope = "member", Target = "~M:Sokoban.Core.Parser.XSBMapParser.LoadLURD(System.String,Sokoban.Model.Stage)")]
[assembly: SuppressMessage("Style", "IDE0300:简化集合初始化", Justification = "<挂起>", Scope = "member", Target = "~F:LogViewerLib.LogViewer.stringBuffers")]
